### ISSUE TITLE
After first Epoch

### ISSUE THREAD

**Issue by AnnualMedia1328** [gorgarp/TorchPass#2]
Traceback (most recent call last):
  File "C:\Users\andri\Downloads\TorchPass-main\TorchPass-main\torchpass.py", line 308, in <module>
    main()
  File "C:\Users\andri\Downloads\TorchPass-main\TorchPass-main\torchpass.py", line 267, in main
    model = train(model, train_loader, val_loader, criterion, optimizer, scheduler, args.epochs)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\andri\Downloads\TorchPass-main\TorchPass-main\torchpass.py", line 165, in train
    torch.save(model.module.state_dict(), 'best_model.pth')
               ^^^^^^^^^^^^
  File "C:\Users\andri\AppData\Local\Programs\Python\Python312\Lib\site-packages\torch\nn\modules\module.py", line 1709, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'PassGen' object has no attribute 'module'. Did you mean: 'modules'?

**Comment by AnnualMedia1328** [comment]
Fixed it by removing "module"

model.state_dict()
model.load_state_dict()

**Comment by gorgarp** [comment]
Thanks for the heads up, should be better now if you care to test
